/** Optimized image data generated by the page via astro:assets `getImage`. */
export interface OptimizedImage {
  src: string;
  srcSet?: string;
}

interface Props {
  image: OptimizedImage;
}

/**
 * Hero — layout follows netsci2026.com: full-bleed photo, title box on the left,
 * date + location chips, round call-to-action button bottom right.
 */
export default function Hero({ image }: Props) {
  return (
    <section className="relative w-full overflow-hidden font-['Rubik']">
      <div className="relative min-h-[85vh] w-full">
        {/* Background photo: Dresden silhouette (DMG / Sylvio Dittrich, Dresden Media Licence DML-BY). */}
        <img
          src={image.src}
          srcSet={image.srcSet}
          sizes="100vw"
          alt="Dresden skyline with Frauenkirche and Hofkirche over the Elbe"
          className="absolute inset-0 h-full w-full object-cover object-center"
          fetchPriority="high"
        />
        <div className="absolute inset-0 bg-black/25" />

        <div className="relative max-w-6xl mx-auto px-4 lg:px-8 pt-28 pb-24">
          {/* Title box */}
          <div className="inline-block bg-[#001A33]/80 backdrop-blur-sm px-7 py-6 md:px-9 md:py-8">
            <h1 className="text-5xl md:text-7xl font-light leading-none text-white">
              NetSci <span className="text-[#D1232A]">2027</span>
            </h1>
            <p className="mt-4 text-xl md:text-2xl font-light text-white leading-snug">
              International School &amp; Conference
              <br />
              on Network Science
            </p>
          </div>

          {/* Date + location chips */}
          <div className="mt-4 flex flex-wrap gap-3">
            <div className="inline-flex items-center gap-2 bg-[#001A33]/80 backdrop-blur-sm px-4 py-3 text-white text-lg font-light">
              <svg className="w-5 h-5 text-[#C9A24B]" fill="none" stroke="currentColor" strokeWidth={1.8} viewBox="0 0 24 24" aria-hidden="true">
                <rect x="3" y="5" width="18" height="16" rx="1" />
                <path d="M3 10h18M8 3v4M16 3v4" />
              </svg>
              May 17–21, 2027
            </div>
            <div className="inline-flex items-center gap-2 bg-[#001A33]/80 backdrop-blur-sm px-4 py-3 text-white text-lg font-light">
              <svg className="w-5 h-5 text-[#C9A24B]" fill="none" stroke="currentColor" strokeWidth={1.8} viewBox="0 0 24 24" aria-hidden="true">
                <path d="M12 21s-7-6.2-7-11.5A7 7 0 0 1 19 9.5C19 14.8 12 21 12 21z" />
                <circle cx="12" cy="9.5" r="2.5" />
              </svg>
              Dresden, Germany
            </div>
          </div>
        </div>

        {/* Round call-to-action, like 2026's "Photos" button */}
        <a
          href="/calls/abstracts"
          className="absolute right-6 bottom-12 md:right-12 w-32 h-32 md:w-36 md:h-36 rounded-full bg-[#003063] hover:bg-[#C9A24B] hover:text-[#001A33] text-white flex flex-col items-center justify-center text-center text-base leading-tight transition-colors shadow-lg"
        >
          Submit an
          <br />
          abstract
          <span aria-hidden="true" className="mt-1">↗</span>
        </a>

        {/* Photo credit (required by DML-BY licence) */}
        <div className="absolute bottom-3 left-4 text-[10px] uppercase tracking-[0.2em] text-white/70">
          Photo · DMG / Sylvio Dittrich (DML-BY)
        </div>
      </div>
    </section>
  );
}
