import { useTranslations } from '../../i18n/utils';

const t = useTranslations();

/** Optimized image data generated by the page via astro:assets `getImage`. */
export interface OptimizedImage {
  src: string;
  srcSet?: string;
}

interface Props {
  image: OptimizedImage;
}

export default function Hero({ image }: Props) {

  return (
    <section className="relative w-full overflow-hidden">
      <div className="relative h-screen w-full">
        {/* Background photo: Dresden silhouette (DMG / Sylvio Dittrich, Dresden Media Licence DML-BY). */}
        <img
          src={image.src}
          srcSet={image.srcSet}
          sizes="100vw"
          alt="Dresden skyline with Frauenkirche and Hofkirche over the Elbe"
          className="absolute inset-0 h-full w-full object-cover object-center"
          fetchPriority="high"
        />

        {/* Dark overlay */}
        <div className="absolute inset-0 bg-black/45" />

        {/* Animated network (src/scripts/networks.ts; static for reduced motion) */}
        <canvas data-network="dark" className="absolute inset-0 h-full w-full pointer-events-none" aria-hidden="true" />

        {/* Photo credit (required by DML-BY licence) */}
        <div className="absolute bottom-4 right-4 text-[10px] uppercase tracking-[0.2em] text-white/70 z-10">
          Photo · DMG / Sylvio Dittrich (DML-BY)
        </div>

        {/* Content */}
        <div className="relative h-full flex flex-col items-center justify-center px-6 text-center pt-16">
          <div className="max-w-5xl mx-auto animate-fade-up">
            <h1
              className="font-sans text-7xl md:text-8xl lg:text-9xl font-light leading-[1] tracking-tight"
              style={{ textShadow: '0 4px 18px rgba(0,0,0,0.55)' }}
            >
              <span className="text-white">NetSci</span>{' '}
              <span style={{ color: '#D1232A' }}>2027</span>
            </h1>

            <p
              className="mt-6 font-sans text-3xl md:text-4xl lg:text-5xl font-light text-white leading-[1.15]"
              style={{ textShadow: '0 2px 12px rgba(0,0,0,0.5)' }}
            >
              {t('hero.title').split('|').map((line, i, arr) => (
                <span key={i}>
                  {line}
                  {i < arr.length - 1 && <br />}
                </span>
              ))}
            </p>

            <p
              className="mt-5 text-white text-lg md:text-xl font-medium tracking-wide"
              style={{ textShadow: '0 1px 6px rgba(0,0,0,0.6)' }}
            >
              {t('hero.dates')}
            </p>

          </div>
        </div>
      </div>
    </section>
  );
}
